In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [5]:
a.size #no. of elements

6

In [6]:
a.ndim #no. of dimensions

2

In [7]:
a.shape #rows , columns

(2, 3)

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [10]:
a1.shape  #returns the size of the array when it's 1-D

(3,)

In [11]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a2.shape

(2, 3)

In [13]:
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
b = np.arange(10) #Creating an array with a range of values 
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
c = np.arange(0,10, 2) #start, stop, step
c

array([0, 2, 4, 6, 8])

In [16]:
d = np.zeros(10) #Defult is float here (makes an all zeros array)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
e = np.zeros(10, dtype=int) #define data type as u like
e

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
f = np.ones((3,10),dtype=int) #making all ones array (1st : dimension , 2nd : no. of elements)
f

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [19]:
g = np.linspace(0, 1, 5)  #Creating an array with a specified number of evenly spaced values #start, stop, step
g                         #note we didn't make it all float as it will make them zeros 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
h = arr.reshape((3, 2))  # Reshape to 3 rows, 2 columns
h

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
i = arr.flatten()  #returns a one-dimensional array containing all elements of the original array
i 

array([1, 2, 3, 4, 5, 6])

In [22]:
k = np.eye(3, dtype=int)  # Create a 3x3 identity matrix
k
                         

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
j = np.eye(4, 4, k=0, dtype=int) #N:ROWS,M*optional:COLUMNS,
j                                #K*optional:Index of the diagonal

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [24]:
l = np.full((10),5)    #creating array of size 10 filled with 5
l

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [25]:
m = np.full((3,10),5)  #3 rows 10 size filled with 5
m

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [26]:
my_list = [1,2,3,4,5]  #convert python list to np aarray
n = np.array(my_list)
n

array([1, 2, 3, 4, 5])

In [27]:
n[2] #accessing any element by index

3

In [28]:
n[2] + n[3]   #summing diff elements by their indexes 

7

In [29]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
a[0,0]  #accessing by row then element

0

In [33]:
a[1,1]

6

In [44]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])           #1,3,3
print(a , "\n""\n")
aa = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])     #2,3,3   
print(aa)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [45]:
print(a.shape , a.ndim , a.size )
print("\n""\n")
print(aa.shape , aa.ndim , aa.size )

(1, 3, 3) 3 9



(2, 3, 3) 3 18


In [46]:
a[0,2,2]

9

In [47]:
print(aa[0,2,2])
print(aa[1,2,2])

9
9
